### ISSUE TITLE
numpy dependecies error

### ISSUE THREAD

**Issue by Theviki20110** [zgchen33/MCGaze#9]
Doing: _python -m pip install mmcv-full==1.4.8 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html_

Looking in links: https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html
Collecting mmcv-full==1.4.8
  Using cached mmcv-full-1.4.8.tar.gz (498 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      
      A module that was compiled using NumPy 1.x cannot be run in
      NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
      versions of NumPy, modules must be compiled with NumPy 2.0.
      Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
      
      If you are a user of the module, the easiest solution will be to
      downgrade to 'numpy<2' or try to upgrade the affected module.
      We expect that some modules will need time to support NumPy 2.
      
      Traceback (most recent call last):  File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qzq000uu/mmcv-full_2509054387c140cd8613f9dc145fd146/setup.py", line 11, in <module>
          import torch
        File "/home/mypath/miniconda3/envs/MCGaze/lib/python3.9/site-packages/torch/__init__.py", line 190, in <module>
          from torch._C import *
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qzq000uu/mmcv-full_2509054387c140cd8613f9dc145fd146/setup.py", line 11, in <module>
          import torch
        File "/home/mypath/miniconda3/envs/MCGaze/lib/python3.9/site-packages/torch/__init__.py", line 190, in <module>
          from torch._C import *
      AttributeError: _ARRAY_API not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by zgchen33** [comment]
Our used numpy version is 1.23.5, I think you should try this before you install mmcv-full:
`pip install numpy==1.23.5`
